name: Build and Push Docker Image

# Trigger workflow khi push code lên branch main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK (để build project Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build project với Maven (hoặc Gradle nếu bạn dùng Gradle)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Login vào Docker Hub (nếu muốn push image lên Docker Hub)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build và Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
